In [16]:
import h5py, sys
import numpy as np

In [41]:
filename = '/nfs/dust/belle2/user/ferber/github-ECLML/out.hdf5'
h5f = h5py.File(filename, 'r')

In [42]:
# energies
n = h5f['n'][:]
n_lm = h5f['n_lm'][:]
x_energy = h5f['x_energy'][:]
y_frac = h5f['y_frac'][:]
y_e = h5f['y_e'][:]

x_theta_local = h5f['x_theta_local'][:]
x_theta = h5f['x_theta'][:]
x_phi_local = h5f['x_phi_local'][:]
x_phi = h5f['x_phi'][:]
x_mass = h5f['x_mass'][:]

mc_energy = h5f['mc_energy'][:]
mc_theta = h5f['mc_theta'][:]
mc_phi = h5f['mc_phi'][:]
mc_pdg = h5f['mc_pdg'][:]
mc_index = h5f['mc_index'][:]
mc_ispairconversion = h5f['mc_ispairconversion'][:]
mc_angle = h5f['mc_angle'][:]

m_cluster_w = h5f['m_cluster_w'][:]
m_cluster_sum = h5f['m_cluster_sum'][:]
m_e_sum = h5f['m_e_sum'][:]

m_exp = h5f['m_exp'][:]
m_run = h5f['m_run'][:]
m_evt = h5f['m_evt'][:]
m_uniqueid = h5f['m_uniqueid'][:]



In [43]:
unique, counts = np.unique(n_lm, return_counts=True)
dict(zip(unique, counts))

{1: 1116, 2: 280, 3: 91, 4: 50}

In [45]:
mc_energy

array([[0.4818609 , 0.19335116, 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       ...,
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]], dtype=float32)

In [ ]:
m_cluster_sum

In [59]:
np.max(m_cluster_w[:,:,3])

0.9999361038208008

In [ ]:
np.set_printoptions(threshold=sys.maxsize)
len(m_e_sum)

In [ ]:
x = np.concatenate((m_cluster_sum, m_e_sum, mc_energy, mc_ispairconversion, mc_pdg, mc_index, mc_angle, n_lm), axis=1)

In [ ]:
x2=x[(x[:,2]>1e-2) & (x[:,3]>1e-2) & (x[:,2]/x[:,4]>0.5) & (x[:,3]/x[:,5]>0.5) & (x[:,6]<1e-2) & (x[:,7]<1e-2),:]

In [ ]:
len(x2)

In [ ]:
x2

In [ ]:
aaaa

In [ ]:
x1 = [[1,2], [3,4]]
x2 = [[10,20], [30,40]]

In [ ]:
def pad_or_truncate(some_list, target_len):
    return some_list[:target_len] + [[0,0]]*(target_len - len(some_list))

In [ ]:
x1_t = np.asmatrix(pad_or_truncate(x1, 100))
x2_t = np.asmatrix(pad_or_truncate(x2, 100))
x=[x1_t, x2_t]

In [ ]:
with h5py.File('xxx.hdf5', 'w', ) as f:
    f.create_dataset('x', data=x, compression="gzip", compression_opts=9)

In [ ]:
h5f = h5py.File('xxx.hdf5', 'r')
xxx = h5f['x'][:]

In [ ]:
len(xxx[0])

In [ ]:
arr=[]
arr = [1 for i in range(5)]
arr

In [ ]:
arr = np.where(arr==1, 12, arr) 

In [ ]:
arr = np.array([])
arr.reshape(2)

In [3]:
np.array([0.0, 0.0])

array([0., 0.])

In [5]:
np.zeros(2)

array([0., 0.])

In [6]:
for ii in range(2):
    print(ii)

0
1


In [8]:
aa = [1,2,3]
aa

[1, 2, 3]

In [15]:
ss = np.sum(aa[:3])
ss

6